### ISSUE TITLE
Android Layer Stack Crash

### ISSUE THREAD

**Issue by armsnyder** [eecs394-spr15/FeldcoLoanRequest#41]

**Comment by armsnyder** [comment]
To solve, you need to change the config/structure.coffee file to contain preloaded views, like so for example:

preloads: [
    {
      id: "applicationForm"
      location: "common#applicationForm"
    },
    {
      id: "clientList"
      location: "common#clientList"
    },
  ]

Then in the controllers, to change views you simply write, for example:
supersonic.ui.layers.replace('applicationForm');

**Comment by FrankAvino** [comment]
I've fixed this for the client list page, but I will fix it for the rest of the workflow once I can access past the supplement view.
